{% set name = "vvm" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vvm-{{ version }}.tar.gz
  sha256: 719b246b1e064457338a61b5e0aa2069ec2298040eff6830ba1b3d010259ec6b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - setuptools-markdown
  run:
    - python >=3.6,<4.0
    - requests >=2.19.0,<3
    - semantic_version >=2.8.1,<3

test:
  imports:
    - vvm
    - vvm.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vyperlang/vvm
  summary: Vyper version management tool
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - spinoch
    - fubuloubu
    - iamdefinitelyahuman
